Aggregation of partial results
marrlab/DomainLab pull request #166
Opened 2023-03-04 16:04 UTC by schoersch

see #152

2023-03-05 09:49 UTC, schoersch commented
@smilesun I've added the new command line arg.
I think this is more flexible then inside the snakefile. Also, the arg allows to intermediate results of a still running benchmark if the state of the output dir can be downloaded to a machine.

2023-03-05 09:51 UTC, schoersch commented
@smilesun Note that I'm not available next week. I don't know if you count this pr to the ones to be merged in the next days. If not, I can provide possible changes next weekend.

2023-03-19 11:28 UTC, smilesun requested changes
Traceback (most recent call last):
  File "/home/sunxd/DomainLab/main_out.py", line 8, in <module>
    if args.bm_config:
AttributeError: 'Namespace' object has no attribute 'bm_config'

2023-03-26 07:30 UTC, schoersch commented
> Traceback (most recent call last): File "/home/sunxd/DomainLab/main_out.py", line 8, in if args.bm_config: AttributeError: 'Namespace' object has no attribute 'bm_config'

Thank you for pointing out, should be fixed now.

2023-03-26 10:46 UTC, smilesun commented on domainlab/utils/generate_benchmark_plots.py
> +    skip_gen: Skips the actual plotting, used to speed up testing.
This should be a new feature for plots?

2023-03-26 11:05 UTC, merged