Add default extensions
marrlab/DomainLab pull request #66
Opened 2023-01-22 10:14 UTC by schoersch

Adds the option to specify the extensions domain independent or omit the specification fully load all default image types.

Note that I added a dataset with different extensions in a single class (mixed-codecs) for testing.

This should also resolve the coverage issue #63.

2023-01-22 11:01 UTC, smilesun requested changes
Could you revert the changes on the images (jpg files)?  Those files should be permanent there and they are binary files (instead of text files) so we do not want to make any modifications on them.

2023-01-22 12:38 UTC, schoersch commented
> Could you revert the changes on the images (jpg files)? Those files should be permanent there and they are binary files (instead of text files) so we do not want to make any modifications on them.

I did not changed any of the existing files. However, in order to test if the filtering by extensions works, I added the mixed_codecs test dataset. Which adds a few additional permanent binary files.

But if you prefer, I can of course remove this dataset and the corresponding tests.

2023-01-22 13:07 UTC, smilesun commented
@schoersch , ah sorry, I misread the path of the images you uploaded, if they are new files, fine for me!

2023-01-22 13:32 UTC, smilesun requested changes
Could you add 1-line docstring """text""" to the functions listed here so we know what each function is doing? 

https://app.codacy.com/gh/marrlab/DomainLab/pullRequest?prid=10989386

2023-01-23 15:23 UTC, schoersch commented on domainlab/dsets/dset_subfolder.py
> +            extensions = ('jpg', 'jpeg', 'png')
The question is if in this case we want to:
1. Read any image file, then we have to make an extensions tuple of all image extensions supported by PIL
2. Or we read any file in the directory. Then we can go for the all_true solution, but the code is crashing when we're stumbling across a non-image file. This is currently the case and reason while the test fails in #69 . I.e. deleting the file *data/mixed_codec/caltech/auto/text.txt* let the tests pass.

2023-01-23 20:03 UTC, smilesun commented
@aliechoes , @peterlienemann  I am done with my review from @schoersch , do you two wanna take a look as well?

2023-01-23 20:04 UTC, smilesun approved these changes

2023-01-23 20:04 UTC, smilesun commented on domainlab/dsets/dset_subfolder.py
> +            extensions = ('jpg', 'jpeg', 'png')
After some long time thinking, i  think it make sense to only raise a warning to the user that we have only 3 default file suffix. The user should be responsible to not to forget to include image files

2023-01-24 15:06 UTC, merged