add plot of confusion matrix
marrlab/DomainLab pull request #89
Opened 2023-02-02 20:55 UTC by xinyuejohn

2023-02-02 21:39 UTC, xinyuejohn commented
@smilesun As you can see from the above image, for each run, there will be one confusion matrix at the end. 

In which way do you suggest saving the confusion matrix? Because for the other results (precision, recall, ... ), every time an extra line will be appended to the .csv file. But for confusion matrix, if is is saved in a .csv file, it is hard to to so.

2023-02-03 08:53 UTC, smilesun commented
@xinyuejohn , this is a feature proposed by @aliechoes , maybe he has some ideas on how the feature should be?

2023-02-03 09:02 UTC, aliechoes commented
Thanks for asking. I would like to propose that we save the confusion matrix as a plot using sklearn.metrics.ConfusionMatrixDisplay

2023-02-03 15:58 UTC, smilesun commented
> @smilesun Also, do you think it is necessary to add the additional dependency of rich package and its output effect?
> 
> If you like it and want to add it, could you please fix the CI test? Because it doesn't use the current .toml file to create the test environment.
@xinyuejohn 
I hope my two commits will resolve this dependences, also I think what @aliechoes suggested is really good, it will be cool to save a pdf or svg to the zoutput folder after a run.

2023-02-03 19:44 UTC, smilesun requested changes
there is codacy issue with trailing white spaces somewhere

2023-02-06 08:35 UTC, smilesun requested changes
please see the individual line wise reviews, especially we want to avoid hard coded strings, welcome for discussions

2023-02-06 21:16 UTC, smilesun commented on domainlab/compos/exp/exp_utils.py
> +        file_path = file_path.removesuffix(".csv")
i added fixedme

2023-02-06 21:17 UTC, smilesun commented
i added some fixeme

2023-02-06 21:17 UTC, merged